### ISSUE TITLE
Use with J2V8

### ISSUE THREAD

**Issue by roman01la** [godmodelabs/ejecta-v8#19]
Hello! Is it possible for EjectaV8 to use an existing instance of V8 provided by J2V8 https://github.com/eclipsesource/J2V8 ?

**Comment by unverbraucht** [comment]
Hi! No, I don't think so. J2V8 is based on Node which brings it's own require() mechanism and other parts that we implemented from scratch to keep them light-weight. It would require either us rebasing our efforts on their code base or J2V8 making it possible to use a plain V8 shared lib instead of node. I don't think either approach is feasible.

**Comment by roman01la** [comment]
@unverbraucht Thanks for your reply.
J2V8 does provide V8 instance (`V8 runtime = V8.createV8Runtime();`). Node stuff is optional. I guess "the right" way of making J2V8 work with EjectaV8 is to rewire all V8 related calls to J2V8?

**Comment by unverbraucht** [comment]
But the V8 instance you get back is a Java-based wrapper around the actual C++ V8 instance, and as I understood it that is always based on the node shared library.

You could try porting our actual canvas implementation to J2V8 - this should be the main feature ejecta-v8 has that J2V8 is missing. Since we use V8 primitives it should be possible. Although the way that we handle value conversion and registering JS / C++ functions for the use by Java will differ from how J2V8 does it and my estimation is that it would involve quite some work to port it.
